# Stat 517 Project #2

## Question 0 [from last time] : Predicting Job Salary

A project for Data Mining at the University of Southampton. The aim is to predict a job's salary with statistical learning, based on information within a job advert.

The main dataset consists of roughly 250k rows representing individual job ads, and a set of variables descriptions about each job ad. A simplified data of 10k could be retrieved at

In [20]:
import pandas as pd # conventional alias

salary = pd.read_csv("http://www.webpages.uidaho.edu/~stevel/Datasets/salary_uk.csv")
salary

,Id,Title,FullDescription,LocationRaw,LocationNormalized,ContractType,ContractTime,Company,Category,SalaryRaw,SalaryNormalized,SourceName
0,12612628,Engineering Systems Analyst,Engineering Systems Analyst Dorking Surrey Sal...,"Dorking, Surrey, Surrey",Dorking,NaN,permanent,Gregory Martin International,Engineering Jobs,20000 - 30000/annum 20-30K,25000,cv-library.co.uk
1,12612830,Stress Engineer Glasgow,Stress Engineer Glasgow Salary **** to **** We...,"Glasgow, Scotland, Scotland",Glasgow,NaN,permanent,Gregory Martin International,Engineering Jobs,25000 - 35000/annum 25-35K,30000,cv-library.co.uk
2,12612844,Modelling and simulation analyst,Mathematical Modeller / Simulation Analyst / O...,"Hampshire, South East, South East",Hampshire,NaN,permanent,Gregory Martin International,Engineering Jobs,20000 - 40000/annum 20-40K,30000,cv-library.co.uk
3,12613049,Engineering Systems Analyst / Mathematical Mod...,Engineering Systems Analyst / Mathematical Mod...,"Surrey, South East, South East",Surrey,NaN,permanent,Gregory Martin International,Engineering Jobs,25000 - 30000/annum 25K-30K negotiable,27500,cv-library.co.uk
4,12613647,"Pioneer, Miser Engineering Systems Analyst","Pioneer, Miser Engineering Systems Analyst Do...","Surrey, South East, South East",Surrey,NaN,permanent,Gregory Martin International,Engineering Jobs,20000 - 30000/annum 20-30K,25000,cv-library.co.uk
5,13179816,Engineering Systems Analyst Water Industry,Engineering Systems Analyst Water Industry Loc...,"Dorking, Surrey, Surrey, Surrey",Dorking,NaN,permanent,Gregory Martin International,Engineering Jobs,20000 - 30000/annum 20K to 30K,25000,cv-library.co.uk
6,14131336,Senior Subsea Pipeline Integrity Engineer,A globally renowned engineering and training c...,"Aberdeen, Borders",UK,NaN,permanent,Indigo 21 Ltd,Engineering Jobs,50000 - 100000/annum,75000,cv-library.co.uk
7,14663196,RECRUITMENT CONSULTANT INDUSTRIAL / COMMERCIA...,THIS IS A LIVE VACANCY NOT A GENERIC ADVERTISE...,"MANCHESTER, Greater Manchester",Manchester,NaN,permanent,Code Blue Recruitment,HR & Recruitment Jobs,18000 - 26000/annum TO 26K BASIC + COMM + BENS,22000,cv-library.co.uk
8,14663197,RECRUITMENT CONSULTANT CONSTRUCTION / TECHNIC...,This is an exceptional opportunity to join a c...,"LEEDS, West Yorkshire",Leeds,NaN,permanent,Code Blue Recruitment,HR & Recruitment Jobs,18000 - 28000/annum 18 - 28K BASIC + COMM + BENS,23000,cv-library.co.uk
9,15395797,Subsea Cables Engineer,A subsea engineering company is looking for an...,"Aberdeen, UK",Aberdeen,NaN,permanent,Indigo 21 Ltd,Engineering Jobs,70000 - 100000/annum,85000,cv-library.co.uk
10,19047429,Trainee Mortgage Advisor East Midlands,"Are you a successful, results driven person? A...",East Midlands,East Midlands,NaN,permanent,Brite Recruitment,Accounting & Finance Jobs,17000 - 25000/annum 17k - 20k OTE 25k,21000,cv-library.co.uk
11,20199757,"PROJECT ENGINEER, PHARMACEUTICAL","PROJECT ENGINEER PHAMACEUTICAL, c**** Excelle...","Witney, Oxfordshire",Witney,NaN,permanent,MatchBox Recruiting Ltd,Healthcare & Nursing Jobs,35000 - 40000/annum c40000 + Excellent Benefits,37500,cv-library.co.uk
12,20638787,Principal Composite Stress Engineer,Aerospace Senior Composite Structures Engineer...,"Avon, South West",Avon,NaN,permanent,Gregory Martin International,Other/General Jobs,40000 - 50000/annum 40K-50K,45000,cv-library.co.uk
13,20638788,Senior Fatigue Damage Tolerance Engineer,Senior Fatigue Static stress (metallic or comp...,"Avon, South West",Avon,NaN,permanent,Gregory Martin International,Other/General Jobs,35000 - 45000/annum 35K-45K,40000,cv-library.co.uk
14,20797143,Chef de Partie Award Winning Restaurant Exce...,A well respected restaurant located in the Der...,Derby Derbyshire East Midlands,Derby,NaN,NaN,Chef Results,Hospitality & Catering Jobs,"Upto 16,000 per annum + Tips (IRO 3K Per Annum)",16000,caterer.com
15,22579462,Quality Engineer,Our client are a leading supplier of precision...,"Gateshead, Tyne and Wear",Gateshead,NaN,permanent,Asset Appointments,Engineering Jobs,22000/annum,22000,cv-library.co.uk
16,22581547,Principal Controls Engineer,A leading Subsea Engineering Company require a...,"Kent, South East",Kent,NaN,permanent,Indigo 21 Ltd,Engineering Jobs,70000 - 100000/annum,85000,cv-library.co.uk
17,22933091,Chef de Partie Award Winning Dining Live In ...,A popular hotel located in Norfolk which is a ...,Norfolk East Anglia,UK,NaN,NaN,Chef Results,Hospitality & Catering Jobs,"18,000 per annum + Tips (IRO 120 Per Month)",18000,caterer.com
18,23528672,Senior Fatigue and Damage Tolerance Engineer,Senior Fatigue Static stress (metallic or comp...,"Avon, South West",Avon,NaN,permanent,Gregory Martin International,Engineering Jobs,34000 - 45000/annum to 45K,39500,cv-library.co.uk
19,23529949,C I Design Engineer,We are currently recruiting on behalf of our c...,"Wolverhampton, West Midlands",Wolverhampton,NaN,permanent,Rullion Engineering Ltd,Engineering Jobs,33000 - 34000/annum + benefits,33500,cv-library.co.uk
20,23530231,Lead Engineers (Stress),Lead Engineers (Stress) Our client provide hig...,"Bristol, Avon, South West, Avon",UK,NaN,permanent,Gregory Martin International,Engineering Jobs,34000 - 45000/annum,39500,cv-library.co.uk
21,24104334,"Relief Chef de Partie Croydon, Surrey Live in",HOTEL AND CONFERENCE VENUE CHAIN RELIEF CHEF...,South Croydon Surrey South East,UK,NaN,NaN,Towngate Personnel,Hospitality & Catering Jobs,Upto 9 per hour,17280,caterer.com
22,24835524,Senior Control and Instrumentation Engineer,Senior Control and Instrumentation Engineer . ...,"Berkshire, South East",Berkshire,NaN,permanent,Gregory Martin International,Engineering Jobs,36000 - 47000/annum 36K-47K,41500,cv-library.co.uk
23,24835548,Control and Instrumentation Engineer,Control and Instrumentation Engineer / C Readi...,"Berkshire, South East",Berkshire,NaN,permanent,Gregory Martin International,Engineering Jobs,28000 - 35000/annum 28K-35K,31500,cv-library.co.uk
24,24854800,Electrical / ICA Engineer,Electrical / ICA Engineer Industry: Environmen...,"Surrey, South East",Surrey,NaN,permanent,Gregory Martin International,Engineering Jobs,"28000 - 37000/annum 28,000 to 37,000",32500,cv-library.co.uk
25,25337172,Pastry Chef for **** red star **** rosette hot...,Pastry Chef for **** red star **** rosette hot...,North East,North East England,NaN,NaN,Clear Selection,Hospitality & Catering Jobs,24000 per annum,24000,caterer.com
26,25434785,Senior Process Engineer,Senior Process Engineer We are seeking applica...,"Berkshire, South East",Berkshire,NaN,permanent,Gregory Martin International,Engineering Jobs,36000 - 47000/annum 36-47K,41500,cv-library.co.uk
27,25452606,CHEF DE PARTIE POSITION IN **** ROSETTE HOTEL ...,CHEF DE PARTIE POSITION IN **** ROSETTE HOTEL ...,North Yorkshire Yorkshire,North Yorkshire,NaN,NaN,Clear Selection,Hospitality & Catering Jobs,16000 per annum + Live In,16000,caterer.com
28,25452680,"Senior Sous Chef for **** rosette kitchen, up ...","Senior Sous Chef for **** rosette kitchen, up ...",North East,North East England,NaN,NaN,Clear Selection,Hospitality & Catering Jobs,26000 per annum,26000,caterer.com
29,25556432,"General Manager Funky, Cool Restaurant Concep...","Senior General Manager – Funky, Cool, Casual R...",West London London South East,East Sheen,NaN,NaN,Bee Recruitment London Ltd,Hospitality & Catering Jobs,"From 28,000 to 35,000 per annum",31500,caterer.com
...,...,...,...,...,...,...,...,...,...,...,...,...
9970,66190658,Care Worker Jobs Brighton,We need to recruit Care Workers in the Brighto...,"Brighton, East Sussex",Brighton,full_time,NaN,NaN,Healthcare & Nursing Jobs,6.48 to 8.50 per hour,14380,careworx.co.uk
9971,66190660,Support Worker Jobs Brighton,We need to recruit Support Worker job seekers ...,"Brighton, East Sussex",Brighton,full_time,NaN,NaN,Healthcare & Nursing Jobs,6.48 to 8.50 per hour,14380,careworx.co.uk
9972,66190661,Support Worker Jobs Hove,We need to recruit Support Worker job seekers ...,"Hove, East Sussex",Hove,full_time,NaN,NaN,Healthcare & Nursing Jobs,6.48 to 8.50 per hour,14380,careworx.co.uk
9973,66190663,Care Assistant Jobs Peacehaven,We need to recruit Care Assistant Job seekers ...,"Peacehaven, East Sussex",Peacehaven,full_time,NaN,NaN,Healthcare & Nursing Jobs,6.48 to 8.50 per hour,14380,careworx.co.uk
9974,66190671,Care Assistant jobs Chatham,Carewatch require care and support workers acr...,"Chatham, Kent",Chatham,part_time,NaN,NaN,Healthcare & Nursing Jobs,7.50 to 11.75 per hour,18480,careworx.co.uk
9975,66190672,Care Assistant jobs Gillingham,Carewatch require care and support workers acr...,"Gillingham, Kent",Gillingham,part_time,NaN,NaN,Healthcare & Nursing Jobs,7.50 to 11.75 per hour,18480,careworx.co.uk
9976,66190676,Support Worker jobs Gillingham,Carewatch require care and support workers acr...,"Gillingham, Kent",Gillingham,part_time,NaN,NaN,Healthcare & Nursing Jobs,7.50 to 11.75 per hour,18480,careworx.co.uk
9977,66190677,Live in Care jobs Southampton,All Care based in Southampton are looking to r...,"Southampton, Hampshire",UK,full_time,NaN,NaN,Healthcare & Nursing Jobs,425 per week,20400,careworx.co.uk
9978,66190679,Care Assistant Jobs Andover,HCA Carer Healthcare Assistant Care Assist...,"Andover, Hampshire",Andover,part_time,NaN,NaN,Healthcare & Nursing Jobs,6.50 to 10.00 per hour,15840,careworx.co.uk
9979,66190683,Care Assistant Jobs Reading,HCA Carer Healthcare Assistant Care Assist...,"Reading, Berkshire",Reading,part_time,NaN,NaN,Healthcare & Nursing Jobs,6.50 to 10.00 per hour,15840,careworx.co.uk
9980,66190692,Experienced Carers – Urgently required,HCA Carer Healthcare Assistant Care Assist...,"Basingstoke, Hampshire",Basingstoke,part_time,NaN,NaN,Healthcare & Nursing Jobs,6.50 to 10.00 per hour,15840,careworx.co.uk
9981,66190693,Dom Care Branch Manager Sheffield,Would you like a rewarding career within the h...,"Sheffield, South Yorkshire",Sheffield,full_time,NaN,NaN,Healthcare & Nursing Jobs,26000 per year,26000,careworx.co.uk
9982,66190695,Optometrist Job Chichester,Black Square are currently working with one of...,"Chichester, West Sussex",Chichester,full_time,NaN,NaN,Healthcare & Nursing Jobs,40k to 60k per year,50000,careworx.co.uk
9983,66190696,Optometrist in Torquay,BlackSquare are looking for an Optometrist to ...,"Torquay, Devon",Torquay,full_time,NaN,NaN,Healthcare & Nursing Jobs,50k to 60k per year,55000,careworx.co.uk
9984,66190697,Optometrist Job Portsmouth,BlackSquare Optometry has an exclusive opportu...,"Portsmouth, Hampshire",Portsmouth,full_time,NaN,NaN,Healthcare & Nursing Jobs,"40,000 to 62,000 per year",51000,careworx.co.uk
9985,66190702,Optometrist Exeter,Optom required for a fantastic independently o...,"Exeter, Devon",Exeter,part_time,NaN,NaN,Healthcare & Nursing Jobs,"70,000 pa per year",70000,careworx.co.uk
9986,66190710,Optometrist Job Swindon,This is an excellent opportunity for a dedicat...,"Swindon, Wiltshire",Swindon,part_time,NaN,NaN,Healthcare & Nursing Jobs,"50,000 per year",50000,careworx.co.uk
9987,66190711,Optometrist Job Fareham,This is an excellent opportunity for a dedicat...,"Fareham, Hampshire",Fareham,part_time,NaN,NaN,Healthcare & Nursing Jobs,"50,000 per year",50000,careworx.co.uk
9988,66190717,Domiciliary Optometrist Hereford,BlackSquare Domiciliary Optometrist Job Heref...,"Hereford, Herefordshire",Hereford,part_time,NaN,NaN,Healthcare & Nursing Jobs,"60,000 per year",60000,careworx.co.uk
9989,66190718,Domiciliary Optometrist Milton Keynes,BlackSquare Domiciliary Optometrist Job Milto...,"Milton Keynes, Buckinghamshire",Milton Keynes,part_time,NaN,NaN,Healthcare & Nursing Jobs,"60,000 per year",60000,careworx.co.uk
9990,66190719,Domiciliary Optometrist Canterbury,BlackSquare Domiciliary Optometrist Job Cant...,"Canterbury, Kent",Canterbury,part_time,NaN,NaN,Healthcare & Nursing Jobs,"60,000 per year",60000,careworx.co.uk
9991,66190721,Domiciliary Optometrist Leeds,Domiciliary Optometrist Job Leeds Domiciliary...,"Leeds, West Yorkshire",Leeds,part_time,NaN,NaN,Healthcare & Nursing Jobs,"60,000 per year",60000,careworx.co.uk
9992,66190722,Laser Optometrist Job Manchester,The company is looking for individuals that ca...,Manchester,Manchester,part_time,NaN,NaN,Healthcare & Nursing Jobs,"47,000 per year",47000,careworx.co.uk
9993,66190723,Senior Optometrist Torquay,This is an excellent opportunity for a dedicat...,Torquay,Torquay,part_time,NaN,NaN,Healthcare & Nursing Jobs,"55,000 per year",55000,careworx.co.uk
9994,66190724,Optometrist Job Bodmin,This is an excellent opportunity for a dedicat...,"Bodmin, Cornwal",Bodmin,part_time,NaN,NaN,Healthcare & Nursing Jobs,"55,000 per year",55000,careworx.co.uk
9995,66190726,Senior Optometrist Ebbe Vale,This is an excellent opportunity for a dedicat...,Ebbe Vale,UK,part_time,NaN,NaN,Healthcare & Nursing Jobs,"52,000 per year",52000,careworx.co.uk
9996,66190728,Domiciliary Optometrist Kent,Domiciliary Optometrist Kent The Company prid...,Kent,Kent,part_time,NaN,NaN,Healthcare & Nursing Jobs,"60,000 per year",60000,careworx.co.uk
9997,66190734,Optometrist Job Hastings,This is an excellent opportunity for a dedicat...,"Hastings, East Sussex",Hastings,part_time,NaN,NaN,Healthcare & Nursing Jobs,"50,000 per year",50000,careworx.co.uk
9998,66190736,Optometrist Job Doncaster,This is an excellent opportunity for a dedicat...,Doncaster,Doncaster,part_time,NaN,NaN,Healthcare & Nursing Jobs,"35,000 to 60,000 per year",47500,careworx.co.uk
9999,66190737,Experienced RHAD Job Lincoln,We provide a community hearing service to thos...,"Lincoln, Lincolnshire",Lincoln,full_time,NaN,NaN,Healthcare & Nursing Jobs,"18,000 to 40,000 per year",29000,careworx.co.uk

The variables are described as follows:

* Id - A unique identifier for each job ad
* Title - A freetext field supplied to us by the job advertiser as the Title of the job ad. Normally this is a summary of the job title or role.
* FullDescription - The full text of the job ad as provided by the job advertiser.
* LocationRaw - The freetext location as provided by the job advertiser.
* LocationNormalized - Adzuna's normalised location from within our own location tree, interpreted by us based on the raw location. Our normaliser is not perfect!
* ContractType - full_time or part_time, interpreted by Adzuna from description or a specific additional field we received from the advertiser.
* ContractTime - permanent or contract, interpreted by Adzuna from description or a specific additional field we received from the advertiser.
* Company - the name of the employer as supplied to us by the job advertiser.
* Category - which of 30 standard job categories this ad fits into, inferred in a very messy way based on the source the ad came from. We know there is a lot of noise and error in this field.
* SalaryRaw - the freetext salary field we received in the job advert from the advertiser.
* SalaryNormalised - the annualised salary interpreted by Adzuna from the raw salary. Note that this is always a single value based on the midpoint of any range found in the raw salary. This is the value we are trying to predict.
* SourceName - the name of the website or advertiser from whom we received the job advert.

Present useful graphics to understand and/or reveal sensible info about the data set. Develop feasible models and compare their predictive accuracies and performance as a whole. Discuss the pros and cons of these models. Summarize and critique your modeling and findings.

## Question 1: World Happiness

According to Wikepedia, the International Day of Happiness is celebrated worldwide every March 20, and was conceptualized and founded by 
philanthropist, activist, 
statesman, and prominent United Nations special advisor Jayme Illien to inspire, mobilize, and advance the global happiness movement.

In 2011, Illien brought the idea and concept of creating a new global day of awareness, the International 
Day of Happiness, to senior United Nations Officials.

The first World Happiness Report was published in April, 2012, in support of the UN High Level Meeting on happiness and well-being. 
Increasingly, happiness is considered to be the proper measure of social progress and 
the goal of public policy. In June 2016 the OECD committed itself “to redefine the growth narrative to put people’s well-being at 
the center of governments’ efforts”. In February 2017, the United Arab Emirates held a full-day World Happiness meeting, as
part of the World Government Summit. 

The 3 related data sets are posted at the Data directory as World_Happiness_2015.csv, World_Happiness_2016.csv, and World_Happiness_2017.csv at my Github.

#### A. Without using any "Happiness" information given, conduct proper Clusterings Analyses and describe these clusters.

#### B. Without using any "Happiness" information given, conduct proper Seriation Analyses and compare the generated order with the "Happiness" ranking.

#### C. Report your findings, including investigations and discussions to support or reflute the following remarks:
  
     1) Norway tops the global happiness rankings for all three years 2015, 2016, and 2017
 
     2) All top ten countries rank highly on all the main features found to support happiness
 
     3) Happiness is both social and personal
 
     4) Unemployment causes a major fall in happiness, and even for those in work the quality of work can cause major variations in happiness
 
     5) China are no happier than most countries, though richer and longer longevity
 
     6) Much of Africa is struggling
 
     7) Happiness has fallen in America

## Question 2: Finding Groupings in Human's Mitochondrial SNP/Mutations Patterns

This question focuses on mitochondria data extracted from the 1000 Genome Project 
dataset; a repository of 1024 individuals' genetic information displayed in terms of S
"mutations". 

A single-nucleotide polymorphism, often abbreviated to SNP (plural: snɪps), is a variation in a single 
nucleotide that occurs at a specific position in the genome, where each variation is present to some appreciable 
degree within a population (e.g. > 1%).

For example, at a specific base position in the human genome, the C nucleotide may appear in most 
individuals, but in a minority of individuals, the position is occupied by an A. This means that there 
is a SNP at this specific position. 

SNPs underlie differences in our susceptibility to disease; a wide range of human diseases, e.g. 
sickle-cell anemia and cystic fibrosis, result from SNPs. The severity of illness and the way the body 
responds to treatments are also manifestations of genetic variations. For example, a single-base mutation 
in the APOE (apolipoprotein E) gene is associated with a lower risk for Alzheimer's disease

In [ ]:
Mt<-read.csv("http://www.webpages.uidaho.edu/~stevel/Datasets/Mt1t.mutate.csv",header=TRUE,sep=',')
Mt<-Mt[-c(1:3),]

dim(Mt) #[1] 1074 2712

For the data set in the file 'Mt1t.mutate.csv', there are 1074 individuals along with 2711 genomic positions.
Each row (i.e. individual) has a profile of SNPs at various genomic positions, with 0 represents no SNP
mutation, and 1 represents a SNP mutation at that position. The first colum represents the given mitochondrial haplogroups.

A haplogroup is a group of individuals that share similar groups of genes together due to sharing a common ancestor.
In human genetics, the haplogroups most commonly studied are Y-chromosome (Y-DNA) haplogroups and 
mitochondrial DNA (mtDNA) haplogroups, each of which can be used to define genetic populations.

#### A. Explore and investigate groupings of individuals. How are your groupings of individuals differ from the given mitochondrial haplogroups?

#### B. Explore and investigate groupings of genomic positions where SNP occurrs. How are your groupings of positions relate to the given mitochondrial haplogroups?

## Question 3: Text Mining on the Bible

The Bible consists of 66 Books mainly written in two languages from a 1500 years time span. They are orderly divided into two Testaments 
(39 Old and 27 New) and seven Sections (5 Law, 12 History, 5 Wisdom, 17 Prophets, 5 Gospels, 13 Paul, and 9 Apostles). 
The Old Testament was originally written in Biblical Hebrew, and the New Testment was written in Koine Greek, which was the common language of Greece 
during the Hellenistic and Roman antiquity. 

Could text mining reveals the structure of these 66 books? Do the text data falls naturally into clusters consistent with the two Testaments and seven Sections structure? ARe there other divisions which are making more sense? Do different parts of the Bible use different sets of characteristic words or words groups?

The purpose of this question is to shed some light to answering them.

Please performe standard text transformations - move all case to lower, remove numbers, remove punctation, remove common stopwords, strip whitespace, and get rid of 
special characters. You will consider n-grams, co-ocurrances, stemming, and term document matrix.

Conducting analyses at the 66 Books level, you will collpase the text of all the verses into the same 66 books before performing analyses.

In [ ]:
ASV<-read.csv("http://www.webpages.uidaho.edu/~stevel/Datasets/bible_asv.csv",header=TRUE,sep=',')

dim(ASV) # [1] 31103 8

attach(ASV)

# Collpase text into the same 66 Books
text.Book=c()
for (i in 1:66) {
  text.Book[i]=paste(text[Books==as.character(unique(Books)[i])],collapse = " ")
}

ASV_Books=data.frame(Books=unique(Books),Testaments=as.factor(c(rep("OT",39),rep("NT",27))), 
                     Sections=as.factor(c(rep("Law",5),rep("History",12),rep("Wisdom",5),rep("Prophets",17),rep("Gospels",5),rep("Paul",13),rep("Apostles",9))),
                     text=text.Book)

dim(ASV_Books)    #[1] 66  4

#### A. What is the optimal number of clusters of these 66 Books? Find these clusters and describe them. Are you surprised at your finding? Why/Why not? Graph and color your clusters (probably on the first two PC's). On the graph, show your clusters in colors, the Testaments in plot symbols, and the Sections in sizes.

        i) How do these clusters match the 2 Testaments? Tabulate and report your clusters missclassification rate versus the 2 Testaments. 
        ii) How do these clusters match the 7 Sections? Tabulate and report your clusters missclassification rate versus the 7 Sections. 

#### B. How would Association Analyses help to reveal characteristic word clusters? Describe these word clusters, and what they are telling you about the Bible. Are the 2 Testaments and the 7 Sections represented by different word clusters?

#### C. How would Seriation Analyses help to reveal the structure of these 66 Books?